### ISSUE TITLE
[DDR] TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by ThatzOkay** [asphyxia-core/plugins#65]
Trying to login using e amuse gives me this error:

May 10 00:39:56 artemis asphyxia-core[1503279]:     at EamuseRootRouter.run (/snapshot/build-env/index.js)
May 10 00:39:56 artemis asphyxia-core[1503279]:     at route (/snapshot/build-env/index.js)
May 10 00:39:58 artemis asphyxia-core[1503279]:   [ddr@asphyxia] error: TypeError: Cannot read properties of null (reading 'singleGrade')
May 10 00:39:58 artemis asphyxia-core[1503279]: TypeError: Cannot read properties of null (reading 'singleGrade')
May 10 00:39:58 artemis asphyxia-core[1503279]:     at userload (/home/thatzokay/asphyxia/plugins/ddr@asphyxia/handlers/usergamedata.ts:79:43)
May 10 00:39:58 artemis asphyxia-core[1503279]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
May 10 00:39:58 artemis asphyxia-core[1503279]:     at usergamedata (/home/thatzokay/asphyxia/plugins/ddr@asphyxia/handlers/usergamedata.ts:18:26)
May 10 00:39:58 artemis asphyxia-core[1503279]:     at EamusePlugin.run (/snapshot/build-env/index.js)
May 10 00:39:58 artemis asphyxia-core[1503279]:     at EamuseRootRouter.run (/snapshot/build-env/index.js)
May 10 00:39:58 artemis asphyxia-core[1503279]:     at route (/snapshot/build-env/index.js)

Game Version: MDX:J:A:A:2022020200 (DDR A20)
Asphyxia CORE: v1.50c
DDR Plugin: v1.0.0

**Comment by ThatzOkay** [comment]
this only seem to happen when using cardio card reader and my Felicia card

**Comment by ThatzOkay** [comment]
And with existing profiel. Weird creating new profile when not using cardio it works then after seems to work to but cardio card or existing profile does not
